/**
 * Valid document short codes - DO NOT EDIT
 * These codes are defined in python/rule_classifier.py
 * Total: 95 valid codes
 */

export const VALID_DOCUMENT_CODES = [
  'BBBDG',
  'BBGD',
  'BBHDDK',
  'BBKTDC',
  'BBKTHT',
  'BBKTSS',
  'BBNT',
  'BKKDT',
  'BLTT',
  'BMT',
  'BVHC',
  'BVN',
  'CCCD',
  'CDLK',
  'CHTGD',
  'CKDC',
  'CKTSR',
  'DCK',
  'DCQDGD',
  'DDCTH',
  'DDK',
  'DDKBD',
  'DGH',
  'DICHUC',
  'DKTC',
  'DKTD',
  'DKXTC',
  'DMD',
  'DMG',
  'DSCG',
  'DSCK',
  'DXCD',
  'DXCMD',
  'DXGD',
  'DXN',
  'DXNTH',
  'DXTHT',
  'GCNC',  // GCN cũ (added manually)
  'GCNM',  // GCN mới (added manually)
  'GKH',
  'GKS',
  'GNT',
  'GPXD',
  'GSND',
  'GTLQ',
  'GUQ',
  'GXNDKLD',
  'GXNNVTC',
  'HCLK',
  'HDBDG',
  'HDCQ',
  'HDTCO',
  'HDTD',
  'HDTHC',
  'HDUQ',
  'HSKT',
  'HTBTH',
  'HTNVTC',
  'KTCKCG',
  'KTCKMG',
  'PCT',
  'PCTSVC',
  'PDPASDD',
  'PKTHS',
  'PLYKDC',
  'PXNKQDD',
  'QDCHTGD',
  'QDCMD',
  'QDDCGD',
  'QDDCQH',
  'QDDCTH',
  'QDGH',
  'QDGTD',
  'QDHG',
  'QDHTSD',
  'QDPDBT',
  'QDPDDG',
  'QDTH',
  'QDTHA',
  'QDTT',
  'QDXP',
  'QR',
  'SDTT',
  'TBCKCG',
  'TBCKMG',
  'TBCNBD',
  'TBMG',
  'TBT',
  'TKT',
  'TTCG',
  'TTHGD',
  'UNKNOWN',
  'VBCTCMD',
  'VBDNCT',
  'VBTC',
  'VBTK',
];

// Helper function to check if a code is valid
export const isValidDocumentCode = (code) => {
  return VALID_DOCUMENT_CODES.includes(code?.toUpperCase());
};

// Get code description (can be expanded later with full mapping)
export const getCodeDescription = (code) => {
  const descriptions = {
    'GCNC': 'Giấy chứng nhận cũ',
    'GCNM': 'Giấy chứng nhận mới',
    'CCCD': 'Căn cước công dân',
    'GKH': 'Giấy kết hôn',
    'GKS': 'Giấy khai sinh',
    'GUQ': 'Giấy ủy quyền',
    'HSKT': 'Hồ sơ kỹ thuật',
    'PCT': 'Phiếu chuyển thông tin nghĩa vụ tài chính',
    'GTLQ': 'Giấy tờ liên quan',
    'UNKNOWN': 'Không xác định',
    // Add more descriptions as needed
  };
  return descriptions[code] || code;
};
